// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Veterinaria.API.Data;

#nullable disable

namespace Veterinaria.API.Migrations
{
    [DbContext(typeof(VeterinariaAPIContext))]
    [Migration("20260324042552_V02")]
    partial class V02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Veterinaria.Modelos.Citas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HorarioId")
                        .HasColumnType("integer");

                    b.Property<int>("MascotaId")
                        .HasColumnType("integer");

                    b.Property<int?>("PersonalAdministrativoId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonalId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoCitaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HorarioId");

                    b.HasIndex("MascotaId");

                    b.HasIndex("PersonalAdministrativoId");

                    b.HasIndex("TipoCitaId");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("Veterinaria.Modelos.Dueños", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido_dueño")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre_dueño")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono_dueño")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("contraseña_dueño")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email_dueño")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dueños");
                });

            modelBuilder.Entity("Veterinaria.Modelos.Especies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre_especie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("Veterinaria.Modelos.Horarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Hora_Inicio")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("Veterinaria.Modelos.Mascotas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DueñoId")
                        .HasColumnType("integer");

                    b.Property<int>("EspecieId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha_Nacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre_Mascota")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DueñoId");

                    b.HasIndex("EspecieId");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("Veterinaria.Modelos.PersonalAdministrativos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido_Personal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre_Personal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono_Personal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("contraseña_Personal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email_Personal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PersonalAdministrativos");
                });

            modelBuilder.Entity("Veterinaria.Modelos.TipoCitas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoCitas");
                });

            modelBuilder.Entity("Veterinaria.Modelos.Citas", b =>
                {
                    b.HasOne("Veterinaria.Modelos.Horarios", "Horario")
                        .WithMany("Citas")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veterinaria.Modelos.Mascotas", "Mascota")
                        .WithMany("Citas")
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veterinaria.Modelos.PersonalAdministrativos", "PersonalAdministrativo")
                        .WithMany("Citas")
                        .HasForeignKey("PersonalAdministrativoId");

                    b.HasOne("Veterinaria.Modelos.TipoCitas", "TipoCita")
                        .WithMany("Citas")
                        .HasForeignKey("TipoCitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Horario");

                    b.Navigation("Mascota");

                    b.Navigation("PersonalAdministrativo");

                    b.Navigation("TipoCita");
                });

            modelBuilder.Entity("Veterinaria.Modelos.Mascotas", b =>
                {
                    b.HasOne("Veterinaria.Modelos.Dueños", "Dueño")
                        .WithMany("Mascotas")
                        .HasForeignKey("DueñoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veterinaria.Modelos.Especies", "Especie")
                        .WithMany("Mascotas")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dueño");

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("Veterinaria.Modelos.Dueños", b =>
                {
                    b.Navigation("Mascotas");
                });

            modelBuilder.Entity("Veterinaria.Modelos.Especies", b =>
                {
                    b.Navigation("Mascotas");
                });

            modelBuilder.Entity("Veterinaria.Modelos.Horarios", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("Veterinaria.Modelos.Mascotas", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("Veterinaria.Modelos.PersonalAdministrativos", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("Veterinaria.Modelos.TipoCitas", b =>
                {
                    b.Navigation("Citas");
                });
#pragma warning restore 612, 618
        }
    }
}
